set-option -sa terminal-overrides ',xterm*:Tc'
set -g mouse on

# Rebind prefix from 'C-b' to 'C-space'
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Make tabs 1-based index
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

# Open new windows in the current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'

run '/opt/homebrew/opt/tpm/share/tpm/tpm'
