"$schema" = 'https://starship.rs/config-schema.json'


format = """
[](#C0C0C0)\
$os\
[](bg:#008939 fg:#C0C0C0)\
$directory\
[](fg:#008939 bg:#005089)\
$git_branch\
$git_status\
$git_state\
$git_commit\
[](fg:#005089)\
$fill\
$aws\
$bun\
$c\
$cmake\
$java\
$localip\
$nodejs\
$python\
$rlang\
$rust\
$package\
$line_break\
$character
"""

[git_commit]
format = '[ \($hash\) $tag ]($style)'
style = "bg:#005089 fg:green"
tag_disabled = false

[git_status]
format = '([\[$all_status$ahead_behind\] ]($style))'
style = "bg:#005089 fg:yellow"

[aws]
format = '[ $symbol($profile) ]($style)'
symbol = ' '
force_display = true
[aws.region_aliases]
us-west-2 = 'west-2'

[directory]
format = "[ $path $read_only ]($style)"
read_only = ""
style = "bg:#008939"

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
style = "bg:#005089"

[fill]
symbol = ' '

[bun]
format = 'via [Bun $version](bold green) '


[c]
format = '[$symbol $version]($style)'
symbol = " "

[cmake]

[java]
symbol = " "

[localip]
disabled = false
style = "cyan"

[nodejs]
format = '[ $symbol$version ]($style)'

[os]
disabled = false
style = "bg:#C1C1C1 fg:#000000"
[os.symbols]
Macos = " "

[package]
format = '[$version]($style)'
display_private = true

[python]
format = '[ $symbol$version ]($style)'
symbol = " "

[rlang]
format = '[ $symbol$version ]($style)'
symbol = "󰟔 "

[rust]
format = '[ $symbol$version ]($style)'
symbol = "󱘗 "
